package compliance

import (
	"bytes"
	"fmt"
)

// Report is the result for a single validation of a commit.
type Report struct {
	// Rule that generated this report.
	Rule Rule
	// Code to identify multiple reports generated by the same rule.
	Code string
	// Severity of the report.
	Severity Severity
	// Message text explaining the cause of the report.
	Message string
	// Location that described by the report.
	Location Location
}

func (r Report) String() string {
	buf := bytes.NewBuffer(nil)

	s := r.Severity
	if r.Severity == 0 {
		s = r.Rule.Severity()
	}

	fmt.Fprintf(buf, "%10s", s.Color().Sprintf("%s", s))
	fmt.Fprintf(buf, " [%s", r.Rule.ID())
	if r.Code != "" {
		fmt.Fprintf(buf, "|%s", r.Code)
	}

	fmt.Fprintf(buf, "] %s", r.Message)

	if r.Location != nil {
		fmt.Fprintf(buf, " (%s)", r.Location)
	}

	return buf.String()
}
