// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package compliance

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Low-1]
	_ = x[Medium-2]
	_ = x[High-3]
	_ = x[Critical-4]
}

const _Severity_name = "LowMediumHighCritical"

var _Severity_index = [...]uint8{0, 3, 9, 13, 21}

func (i Severity) String() string {
	i -= 1
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
